name: Release Package

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      prerelease:
        description: "Create as prerelease"
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Build package
        run: bun run build

      - name: Verify build output
        run: |
          echo "Checking dist folder contents:"
          ls -la dist/ || echo "dist folder not found"
          echo "Checking if main entry point exists:"
          ls -la dist/index.js || echo "dist/index.js not found"

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        id: version
        run: |
          # Install semver for version bumping
          npm install -g semver

          CURRENT_VERSION="${{ steps.current_version.outputs.current }}"
          NEW_VERSION=$(semver -i ${{ github.event.inputs.version_type }} $CURRENT_VERSION)

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version

      - name: Update package.json and commit
        run: |
          git add package.json
          git add -f dist/
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }} with built files"
          git push origin main

      - name: Create Git tag
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

      - name: Generate changelog
        id: changelog
        run: |
          # Get commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Create changelog
          CHANGELOG="## What's Changed"$'\n\n'"$COMMITS"

          # Handle multiline output for GitHub Actions
          {
            echo 'changelog<<EOF'
            echo "$CHANGELOG"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Create distribution archive
        run: |
          if [ -d "dist" ]; then
            echo "Creating distribution archive from dist folder"
            cd dist
            zip -r ../dist.zip .
            cd ..
          else
            echo "Warning: dist folder not found, creating empty archive"
            touch empty.txt
            zip dist.zip empty.txt
            rm empty.txt
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          body: |
            # Release ${{ steps.version.outputs.tag }}

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ### NPM/Yarn/Bun
            ```bash
            npm install @onkernel/cu-playwright-ts@${{ steps.version.outputs.new_version }}
            # or
            yarn add @onkernel/cu-playwright-ts@${{ steps.version.outputs.new_version }}
            # or  
            bun add @onkernel/cu-playwright-ts@${{ steps.version.outputs.new_version }}
            ```

            ### GitHub Dependency
            ```json
            {
              "dependencies": {
                "@onkernel/cu-playwright-ts": "github:bigboateng/cu-playwright-ts#${{ steps.version.outputs.tag }}"
              }
            }
            ```
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            dist.zip
            package.json
